# Generated by Django 3.2 on 2021-12-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
