# Generated by Django 3.2 on 2021-12-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_meal_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'meal', 'verbose_name_plural': 'meals'},
        ),
    ]
