# Generated by Django 3.2 on 2022-01-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_size', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10+', '10+')], default='4', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], default='12:00', max_length=5)),
                ('table_size', models.ForeignKey(default='4', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='bookings.tables')),
            ],
        ),
    ]
