# Generated by Django 3.2 on 2022-01-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
