# Generated by Django 3.2 on 2022-01-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tables',
            options={'verbose_name': 'table', 'verbose_name_plural': 'tables'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='table_size',
            field=models.ForeignKey(default='2', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='bookings.tables'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='table_size',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10+', '10+')], default='2', max_length=200, null=True),
        ),
    ]
