# Generated by Django 3.2 on 2022-01-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Booking awaiting restaurant confirmation'), (1, 'Booking confirmed')], default=0),
        ),
    ]
