# Generated by Django 3.2 on 2022-01-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booking awaiting restaurant confirmation', 'Booking awaiting restaurant confirmation'), ('Booking confirmed', 'Booking confirmed')], default='Booking awaiting restaurant confirmation', max_length=50),
        ),
    ]
